apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- is.yaml
- deployment.yaml
- service.yaml
- route.yaml
- project-helm-chart-repository.yaml
- namespace.yaml

namespace: helmchart3
